### ISSUE TITLE
Parsing backtrace doesn't work in ruby 1.8.7

### ISSUE THREAD

**Issue by dkowis** [jordansissel/ruby-cabin#14]
So if you do, you get a nasty exception: 

```
undefined method `[]' for nil:NilClass
/home/dkowis/.rvm/gems/ruby-1.8.7-p371/gems/cabin-0.6.0/lib/cabin/mixins/logger.rb:112:in `debugharder'
/home/dkowis/.rvm/gems/ruby-1.8.7-p371/gems/cabin-0.6.0/lib/cabin/mixins/logger.rb:100:in `_log'
/home/dkowis/.rvm/gems/ruby-1.8.7-p371/gems/cabin-0.6.0/lib/cabin/mixins/logger.rb:79:in `log_with_level'
/home/dkowis/.rvm/gems/ruby-1.8.7-p371/gems/cabin-0.6.0/lib/cabin/mixins/logger.rb:64:in `debug'
./lib/tasks/packaging.rake:87
```

Diagnosing with puts'es from a project of mine:
This stems from the `BACKTRACE_RE`:

`BACKTRACE_RE: (?-mix:([^:]+):([0-9]+):in`(.*)')`

The `callinfo` variable when used in a rake task is: 

`CALLINFO: ./lib/tasks/packaging.rake:87`

So yeah, that regexp doesn't match, and then it's all over :(
